// frontend-react/src/pages/admin/Employees.js
import React, { useState, useEffect } from 'react';
import { api } from '@/App';
import { toast } from 'sonner';
import { Plus, Edit2, Trash2, ShieldCheck, Key } from 'lucide-react';

const ROLE_LABELS = { administrateur: 'Administrateur', gestionnaire: 'Gestionnaire', technicien: 'Technicien', clinicien: 'Clinicien', lecture: 'Lecture seule' };
const ROLE_COLORS = { administrateur: 'bg-red-100 text-red-700', gestionnaire: 'bg-blue-100 text-blue-700', technicien: 'bg-amber-100 text-amber-700', clinicien: 'bg-green-100 text-green-700', lecture: 'bg-slate-100 text-slate-600' };

export default function Employees() {
  const [employees, setEmployees] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [editItem, setEditItem] = useState(null);
  const [form, setForm] = useState({
    email: '', password: '', first_name: '', last_name: '', role: 'clinicien', pin: '', card_id: '',
  });

  const fetchData = async () => {
    setLoading(true);
    try {
      const res = await api.get('/employees');
      setEmployees(res.data);
    } catch (err) {
      toast.error(err.response?.data?.detail || 'Erreur');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchData(); }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      if (editItem) {
        const payload = { ...form };
        if (!payload.password) delete payload.password;
        if (!payload.pin) delete payload.pin;
        await api.put(`/employees/${editItem.id}`, payload);
        toast.success('Employé mis à jour');
      } else {
        await api.post('/employees', form);
        toast.success('Employé créé');
      }
      setShowForm(false);
      setEditItem(null);
      setForm({ email: '', password: '', first_name: '', last_name: '', role: 'clinicien', pin: '', card_id: '' });
      fetchData();
    } catch (err) {
      toast.error(err.response?.data?.detail || 'Erreur');
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Supprimer cet employé ?')) return;
    try {
      await api.delete(`/employees/${id}`);
      toast.success('Employé supprimé');
      fetchData();
    } catch (err) {
      toast.error(err.response?.data?.detail || 'Erreur');
    }
  };

  const openEdit = (emp) => {
    setEditItem(emp);
    setForm({
      email: emp.email, password: '', first_name: emp.first_name, last_name: emp.last_name,
      role: emp.role, pin: '', card_id: emp.card_id || '',
    });
    setShowForm(true);
  };

  return (
    <div className="p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Employés</h1>
          <p className="text-sm text-slate-500 mt-0.5">Gestion des comptes et des rôles</p>
        </div>
        <button data-testid="create-employee-btn" onClick={() => { setEditItem(null); setShowForm(true); }}
          className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-700">
          <Plus className="w-4 h-4" /> Nouvel employé
        </button>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-slate-50">
            <tr>
              <th className="text-left px-4 py-3 font-medium text-slate-500">Nom</th>
              <th className="text-left px-4 py-3 font-medium text-slate-500">Email</th>
              <th className="text-left px-4 py-3 font-medium text-slate-500">Rôle</th>
              <th className="text-left px-4 py-3 font-medium text-slate-500">Carte</th>
              <th className="text-left px-4 py-3 font-medium text-slate-500">NIP</th>
              <th className="px-4 py-3"></th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {loading ? (
              <tr><td colSpan="6" className="px-4 py-8 text-center text-slate-400">Chargement...</td></tr>
            ) : employees.length === 0 ? (
              <tr><td colSpan="6" className="px-4 py-8 text-center text-slate-400">Aucun employé</td></tr>
            ) : employees.map(emp => (
              <tr key={emp.id} className="hover:bg-slate-50">
                <td className="px-4 py-3 font-medium">{emp.first_name} {emp.last_name}</td>
                <td className="px-4 py-3 text-slate-600">{emp.email}</td>
                <td className="px-4 py-3">
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${ROLE_COLORS[emp.role] || 'bg-slate-100'}`}>
                    {ROLE_LABELS[emp.role] || emp.role}
                  </span>
                </td>
                <td className="px-4 py-3 text-slate-600 font-mono text-xs">{emp.card_id ? `****${emp.card_id.slice(-4)}` : '—'}</td>
                <td className="px-4 py-3">
                  {emp.has_pin ? <Key className="w-3.5 h-3.5 text-green-500" /> : <span className="text-slate-300">—</span>}
                </td>
                <td className="px-4 py-3">
                  <div className="flex gap-1">
                    <button onClick={() => openEdit(emp)} className="p-1 hover:bg-slate-100 rounded"><Edit2 className="w-3.5 h-3.5 text-slate-400" /></button>
                    <button onClick={() => handleDelete(emp.id)} className="p-1 hover:bg-red-50 rounded"><Trash2 className="w-3.5 h-3.5 text-red-400" /></button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Modal */}
      {showForm && (
        <div className="fixed inset-0 bg-black/30 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl p-6 w-full max-w-md">
            <h2 className="text-lg font-bold mb-4">{editItem ? 'Modifier l\'employé' : 'Nouvel employé'}</h2>
            <form onSubmit={handleSubmit} className="space-y-3">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-sm font-medium mb-1">Prénom *</label>
                  <input className="w-full border rounded-lg px-3 py-2 text-sm" required
                    value={form.first_name} onChange={e => setForm({ ...form, first_name: e.target.value })} />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1">Nom *</label>
                  <input className="w-full border rounded-lg px-3 py-2 text-sm" required
                    value={form.last_name} onChange={e => setForm({ ...form, last_name: e.target.value })} />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Email *</label>
                <input type="email" className="w-full border rounded-lg px-3 py-2 text-sm" required
                  value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">{editItem ? 'Nouveau mot de passe (vide = inchangé)' : 'Mot de passe *'}</label>
                <input type="password" className="w-full border rounded-lg px-3 py-2 text-sm" required={!editItem}
                  value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Rôle *</label>
                <select className="w-full border rounded-lg px-3 py-2 text-sm" required
                  value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}>
                  {Object.entries(ROLE_LABELS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
                </select>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-sm font-medium mb-1">NIP (4+ chiffres)</label>
                  <input className="w-full border rounded-lg px-3 py-2 text-sm" placeholder={editItem ? 'Vide = inchangé' : ''}
                    value={form.pin} onChange={e => setForm({ ...form, pin: e.target.value })} />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1">ID Carte</label>
                  <input className="w-full border rounded-lg px-3 py-2 text-sm"
                    value={form.card_id} onChange={e => setForm({ ...form, card_id: e.target.value })} />
                </div>
              </div>
              <div className="flex gap-2 pt-2">
                <button type="button" onClick={() => { setShowForm(false); setEditItem(null); }}
                  className="flex-1 border rounded-lg py-2 text-sm hover:bg-slate-50">Annuler</button>
                <button type="submit"
                  className="flex-1 bg-blue-600 text-white rounded-lg py-2 text-sm font-medium hover:bg-blue-700">{editItem ? 'Mettre à jour' : 'Créer'}</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

// frontend/src/app/management/employees/employees.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { InputTextModule } from 'primeng/inputtext';
import { TagModule } from 'primeng/tag';
import { ToastModule } from 'primeng/toast';
import { SelectModule } from 'primeng/select';
import { MessageService } from 'primeng/api';
import { ApiService } from '../../core/services/api.service';

@Component({
  selector: 'app-employees',
  standalone: true,
  imports: [CommonModule, FormsModule, TableModule, ButtonModule, DialogModule, InputTextModule, TagModule, ToastModule, SelectModule],
  providers: [MessageService],
  template: `
    <p-toast />
    <div class="p-6 page-enter" data-testid="management-employees">
      <div class="page-header">
        <h1>Employ\u00e9s</h1>
        <p-button label="Nouvel employ\u00e9" icon="pi pi-plus" (onClick)="openCreate()" data-testid="btn-new-employee" />
      </div>
      <p-table [value]="employees" styleClass="p-datatable-sm" data-testid="employees-table">
        <ng-template pTemplate="header">
          <tr><th>Pr\u00e9nom</th><th>Nom</th><th>Email</th><th>R\u00f4le</th><th class="text-center" style="width: 5rem;">Actions</th></tr>
        </ng-template>
        <ng-template pTemplate="body" let-e>
          <tr>
            <td>{{ e.first_name }}</td><td>{{ e.last_name }}</td><td>{{ e.email }}</td>
            <td><p-tag [value]="e.role" /></td>
            <td class="text-center">
              <div class="flex items-center justify-center gap-1">
                <p-button icon="pi pi-pencil" [text]="true" size="small" severity="info" (onClick)="openEdit(e)" [attr.data-testid]="'edit-employee-' + e.id" />
                <p-button icon="pi pi-trash" [text]="true" size="small" severity="danger" (onClick)="deleteEmployee(e)" [attr.data-testid]="'delete-employee-' + e.id" />
              </div>
            </td>
          </tr>
        </ng-template>
      </p-table>
    </div>
    <p-dialog [header]="editingId ? 'Modifier employ\u00e9' : 'Nouvel employ\u00e9'" [(visible)]="showForm" [modal]="true" [style]="{width: '450px'}">
      <div class="flex flex-col gap-3">
        <div class="grid grid-cols-2 gap-3">
          <div><label class="block text-sm mb-1" style="color: var(--cdmi-text-secondary);">Pr\u00e9nom *</label><input pInputText [(ngModel)]="form.first_name" class="w-full" data-testid="emp-firstname" /></div>
          <div><label class="block text-sm mb-1" style="color: var(--cdmi-text-secondary);">Nom *</label><input pInputText [(ngModel)]="form.last_name" class="w-full" data-testid="emp-lastname" /></div>
        </div>
        <div><label class="block text-sm mb-1" style="color: var(--cdmi-text-secondary);">Email *</label><input pInputText [(ngModel)]="form.email" class="w-full" data-testid="emp-email" /></div>
        @if (!editingId) {
          <div><label class="block text-sm mb-1" style="color: var(--cdmi-text-secondary);">Mot de passe *</label><input pInputText type="password" [(ngModel)]="form.password" class="w-full" data-testid="emp-password" /></div>
        }
        <div class="grid grid-cols-2 gap-3">
          <div><label class="block text-sm mb-1" style="color: var(--cdmi-text-secondary);">R\u00f4le *</label><p-select [(ngModel)]="form.role" [options]="roleOptions" optionLabel="label" optionValue="value" placeholder="Choisir un r\u00f4le" class="w-full" appendTo="body" data-testid="emp-role" /></div>
          <div><label class="block text-sm mb-1" style="color: var(--cdmi-text-secondary);">NIP</label><input pInputText [(ngModel)]="form.pin" class="w-full" data-testid="emp-pin" /></div>
        </div>
      </div>
      <ng-template pTemplate="footer">
        <p-button label="Annuler" severity="secondary" (onClick)="showForm = false" />
        <p-button [label]="editingId ? 'Enregistrer' : 'Cr\u00e9er'" (onClick)="save()" data-testid="emp-submit" />
      </ng-template>
    </p-dialog>
  `,
})
export class EmployeesComponent implements OnInit {
  employees: any[] = [];
  showForm = false;
  editingId: string | null = null;
  form: any = {};
  roleOptions = [
    { value: 'administrateur', label: 'Administrateur' },
    { value: 'clinicien', label: 'Clinicien' },
    { value: 'technicien', label: 'Technicien' },
    { value: 'infirmier', label: 'Infirmier' },
    { value: 'gestionnaire', label: 'Gestionnaire' },
  ];
  constructor(private api: ApiService, private msg: MessageService) {}
  ngOnInit() { this.load(); }
  load() { this.api.get<any[]>('/employees').subscribe(d => this.employees = d); }

  openCreate() { this.editingId = null; this.form = {}; this.showForm = true; }
  openEdit(e: any) {
    this.editingId = e.id;
    this.form = { first_name: e.first_name, last_name: e.last_name, email: e.email, role: e.role, pin: e.pin || '' };
    this.showForm = true;
  }

  save() {
    if (this.editingId) {
      this.api.put(`/employees/${this.editingId}`, this.form).subscribe({
        next: () => { this.showForm = false; this.form = {}; this.load(); this.msg.add({ severity: 'success', summary: 'Employ\u00e9 modifi\u00e9' }); },
        error: (e) => this.msg.add({ severity: 'error', summary: e.error?.message || 'Erreur' }),
      });
    } else {
      this.api.post('/employees', this.form).subscribe({
        next: () => { this.showForm = false; this.form = {}; this.load(); this.msg.add({ severity: 'success', summary: 'Employ\u00e9 cr\u00e9\u00e9' }); },
        error: (e) => this.msg.add({ severity: 'error', summary: e.error?.message || 'Erreur' }),
      });
    }
  }

  deleteEmployee(e: any) {
    this.api.delete(`/employees/${e.id}`).subscribe({ next: () => this.load(), error: (err) => this.msg.add({ severity: 'error', summary: err.error?.message || 'Erreur' }) });
  }
}
