// frontend/src/app/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { PasswordModule } from 'primeng/password';
import { MessageModule } from 'primeng/message';
import { AuthService } from './core/services/auth.service';
import { ThemeService } from './core/services/theme.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, ButtonModule, InputTextModule, PasswordModule, MessageModule],
  template: `
    <div class="min-h-screen flex items-center justify-center bg-surface-900" style="position: relative;" data-testid="login-page">
      <button (click)="theme.toggle()" class="theme-toggle" style="position: absolute; top: 1.5rem; right: 1.5rem;" data-testid="login-theme-toggle" [title]="theme.isDark ? 'Mode clair' : 'Mode sombre'">
        <i [class]="theme.isDark ? 'pi pi-sun' : 'pi pi-moon'"></i>
      </button>
      <div class="login-card w-full max-w-md">
        <div class="text-center mb-6">
          <h1 class="text-3xl font-bold text-white">Chrono DMI</h1>
          <p class="text-surface-400 mt-1">Gestion des dispositifs medicaux</p>
        </div>
        @if (error) {
          <p-message severity="error" [text]="error" styleClass="w-full mb-4" />
        }
        <div class="flex flex-col gap-4">
          <div>
            <label class="block text-sm font-medium text-surface-400 mb-1">Email</label>
            <input pInputText [(ngModel)]="email" class="w-full" placeholder="votre@email.com" data-testid="login-email" />
          </div>
          <div>
            <label class="block text-sm font-medium text-surface-400 mb-1">Mot de passe</label>
            <p-password [(ngModel)]="password" [feedback]="false" [toggleMask]="true" styleClass="w-full" inputStyleClass="w-full" (keydown.enter)="onLogin()" data-testid="login-password" />
          </div>
          <p-button label="Se connecter" (onClick)="onLogin()" [loading]="loading" styleClass="w-full" data-testid="login-submit" />
        </div>
        <div class="text-center mt-6">
          <a routerLink="/production/login" class="text-sm text-purple-400 hover:underline" data-testid="goto-production">Acceder a Production</a>
        </div>
      </div>
    </div>
  `,
})
export class LoginComponent {
  private auth = inject(AuthService);
  private router = inject(Router);
  theme = inject(ThemeService);
  email = '';
  password = '';
  loading = false;
  error = '';

  onLogin() {
    this.loading = true;
    this.error = '';
    this.auth.login(this.email, this.password).subscribe({
      next: () => { this.router.navigate(['/management/interventions']); },
      error: (err: any) => { this.error = err.error?.message || 'Identifiants invalides'; this.loading = false; },
    });
  }
}

// frontend-react/src/pages/Login.js
import React, { useState } from 'react';
import { toast } from 'sonner';
import axios from 'axios';
import { Eye, EyeOff, Monitor, Tablet } from 'lucide-react';

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

export default function Login({ onLogin }) {
  const [formData, setFormData] = useState({ email: '', password: '' });
  const [loading, setLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      const res = await axios.post(`${API}/auth/login`, formData);
      toast.success('Connexion réussie');
      onLogin(res.data.access_token, res.data.user, 'management');
    } catch (error) {
      const detail = error.response?.data?.detail;
      toast.error(typeof detail === 'string' ? detail : 'Erreur de connexion');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-50 to-blue-50">
      <div className="w-full max-w-md p-8">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-blue-700 tracking-tight">Chrono DMI</h1>
          <p className="text-sm text-slate-500 mt-1">Gestion des dispositifs médicaux implantables</p>
        </div>

        <div className="bg-white rounded-xl shadow-lg p-8 border border-slate-200">
          <div className="flex items-center gap-2 mb-6 pb-4 border-b">
            <Monitor className="w-5 h-5 text-blue-600" />
            <h2 className="font-semibold text-lg">Gestion</h2>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Email</label>
              <input
                data-testid="login-email"
                type="email"
                className="w-full px-3 py-2.5 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none"
                placeholder="exemple@hopital.com"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                required
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Mot de passe</label>
              <div className="relative">
                <input
                  data-testid="login-password"
                  type={showPassword ? 'text' : 'password'}
                  className="w-full px-3 py-2.5 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none pr-10"
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  required
                />
                <button type="button" className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400"
                  onClick={() => setShowPassword(!showPassword)}>
                  {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </button>
              </div>
            </div>
            <button
              data-testid="login-submit"
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 text-white py-2.5 rounded-lg font-medium hover:bg-blue-700 disabled:opacity-50 transition-colors"
            >
              {loading ? 'Connexion...' : 'Se connecter'}
            </button>
          </form>

          <div className="mt-6 pt-4 border-t text-center">
            <a
              data-testid="go-to-light-client"
              href="/production/login"
              className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-blue-600 transition-colors"
            >
              <Tablet className="w-4 h-4" />
              Accéder à Production
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
